packages:
  - apps/*
  - packages/*
  - '@weapp-core/*'
  - website
  - '!**/test/**'

onlyBuiltDependencies:
  - '@swc/core'
  - '@weapp-tailwindcss/merge'
  - rolldown
  - weapp-tailwindcss

# nodeLinker: hoisted
shamefullyHoist: true
