# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
base = "website-weapp-vite/"
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
